### ISSUE TITLE
Add `add-to-init-file' 

### ISSUE THREAD

**Issue by rudolfochrist** [rudolfochrist/ql-https#4]
Just like Quicklisp, add a function `add-to-init-file` that writes the startup/initialize code snippet in the init file of the given CL implementation. 

see: https://riptutorial.com/common-lisp/example/20147/initialization-files

**Comment by bo-tato** [comment]
yea that is better idea than just adding sbcl specific instructions. Since it's already on top of quicklisp and quicklisp already has function `add-to-init-file` that's tested and works on all CL implementations it makes sense to just use it, but I'm not sure what would be the right way, some ideas:
1) write the ql-https startup code to `quicklisp/setup.lisp`, now `(ql:add-to-init-file)` works as it just adds code to load `quicklisp/setup.lisp`
2) overwrite `ql-impl-util::write-init-forms` or `ql-impl-util::quicklisp-init-file-form` which are called by `(ql:add-to-init-file)` with the ql-https setup code
3) make our own simple `add-to-init-file` function by just writing the ql-https startup code to `(ql-impl-util::init-file-name)`
4) rather than overwriting or using private methods from quicklisp make our own copy of whatever private function (ql-impl-util::init-file-name) we want to use
5) implement from scratch

I think 1 is the simplest, it has the problem that we clobber quicklisp's setup file so now the user can only load ql-https and not plain quicklisp. But I don't think it's really a problem as presumably if a user installed ql-https they want to always use it instead of quicklisp. Which option would you recommend, or something else?

**Comment by rudolfochrist** [comment]
I have the fifth option in mind. In don't want to mess with QL code or overwrite and redefine stuff. I imagine a function 
`add-to-init-file` that checks which CL implementation is currently used, checks if the rc file exists (if not 
`add-to-init-file` creates it) and writes the initialization snippet to the rc file.

**Comment by bo-tato** [comment]
Hey, I finally get back to this :) I'm thinking first option might be needed, as I ran into an issue with CIEL where it does `(load "~/quicklisp/setup")` which fails as with ql-https there is no `~/quicklisp/setup` file. I had to put the ql-https setup code in there to make it work. [Searching github](https://github.com/search?q=load+quicklisp%2Fsetup&type=code) it seems there is a decent number of lisp projects that expect to be able to load quicklisp by loading that `~/quicklisp/setup.lisp`. So for those to work with `ql-https` we have to put the ql-https setup code anyway in `quicklisp/setup.lisp`, and if that's the case then we can just use `(ql:add-to-init-file)` without any changes as it just adds code to the rc file of each lisp implementation to load `~/quicklisp/setup.lisp` on startup

**Comment by rudolfochrist** [comment]
Interesting. Feel free to come up with a solution then. The important step is to have `ql-https` loaded *before* `(quicklisp:setup)` is evaluated. 

On the other hand, having an implicit dependency to Quicklisp by referencing `~/quicklisp/setup.lisp` is a design flaw in my opinion. There are people out there (myself included) that don't use Quicklisp and therefore have no need for `ql-https` at all. How are they supposed to work with this decent number of lisp projects?

**Comment by bo-tato** [comment]
> having an implicit dependency to Quicklisp by referencing ~/quicklisp/setup.lisp is a design flaw in my opinion.

I agree, I haven't looked into the others but in the case of [CIEL](https://github.com/ciel-lang/CIEL/) it is assuming in many places that dependencies are downloaded with quicklisp.

> There are people out there (myself included) that don't use Quicklisp

Interesting, what do you use? I've been wanting to look into nix, I think it has a quicklisp importer so it can use everything packaged in quicklisp

**Comment by bo-tato** [comment]
I made a simple bash installer script that does all the installation instructions https://github.com/rudolfochrist/ql-https/pull/7
`ql-https` is loaded before `(quicklisp:setup)` as `(ql:add-to-init-file)` simply adds to your lisp implementations init rc file code to load `~/quicklisp/setup.lisp` and the installer writes in `~/quicklisp/setup.lisp` the ql-https setup code, not quicklisp setup.

**Comment by rudolfochrist** [comment]
> Interesting, what do you use?

I'm using [ocicl/ocicl](https://github.com/ocicl/ocicl) now. Dependencies are downloaded over HTTPS and does project-local dependencies.

**Comment by bo-tato** [comment]
Interesting I'll read about it

**Comment by rudolfochrist** [comment]
Fixed in #7
